version: '3.1'

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=webflux_c
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
