spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8001/api/v1/user
          predicates:
            - Path=/user
        - id: post_service
          uri: http://localhost:8002/post
          predicates:
            - Path=/post
        - id: comment_service
          uri: http://localhost:8003/comment
          predicates:
            - Path=/comment

    security:

port:
  server: 8080