spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mvc_service_a
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-description: Initial
    baseline-on-migrate: true
    schemas: public

server:
  port: 8081